[2021-08-20 08:16:53,256] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1651036873, epoch=131638) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:53,258] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1651036873, epoch=131638), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:53,814] WARN Client session timed out, have not heard from server in 12001ms for sessionid 0x8001dae61d70001 (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:53,815] INFO Client session timed out, have not heard from server in 12001ms for sessionid 0x8001dae61d70001, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:54,912] INFO [GroupCoordinator 87]: Member consumer-console-consumer-82656-1-dec06f80-1c7a-40bb-9159-94be70d640e1 in group console-consumer-82656 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:16:54,913] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-82656 in state PreparingRebalance with old generation 1 (__consumer_offsets-18) (reason: removing member consumer-console-consumer-82656-1-dec06f80-1c7a-40bb-9159-94be70d640e1 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:16:54,913] INFO [GroupCoordinator 87]: Group console-consumer-82656 with generation 2 is now empty (__consumer_offsets-18) (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:16:54,914] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:54,914] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:16:54,914] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:55,089] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:55,090] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:16:55,090] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:55,258] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:55,258] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1651036873, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:55,259] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_error_log-0=PartitionData(fetchOffset=672, logStartOffset=7, maxBytes=1048576, currentLeaderEpoch=Optional[9], lastFetchedEpoch=Optional[9]), myfleet_info_log-0=PartitionData(fetchOffset=95, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty), myfleet_error_log-1=PartitionData(fetchOffset=683, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[8], lastFetchedEpoch=Optional[8]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty)}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1651036873, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:55,440] INFO [GroupCoordinator 87]: Member consumer-console-consumer-25563-1-33488471-d64f-4d4d-a9b7-80bbe2559b27 in group console-consumer-25563 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:16:55,441] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-25563 in state PreparingRebalance with old generation 1 (__consumer_offsets-32) (reason: removing member consumer-console-consumer-25563-1-33488471-d64f-4d4d-a9b7-80bbe2559b27 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:16:55,441] INFO [GroupCoordinator 87]: Group console-consumer-25563 with generation 2 is now empty (__consumer_offsets-32) (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:16:56,200] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:56,201] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:16:56,201] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:57,140] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:57,140] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:16:57,141] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:57,259] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:57,259] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1651036873, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:57,260] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_error_log-0=PartitionData(fetchOffset=672, logStartOffset=7, maxBytes=1048576, currentLeaderEpoch=Optional[9], lastFetchedEpoch=Optional[9]), myfleet_info_log-0=PartitionData(fetchOffset=95, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty), myfleet_error_log-1=PartitionData(fetchOffset=683, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[8], lastFetchedEpoch=Optional[8]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty)}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1651036873, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:57,890] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:57,890] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:16:57,890] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:59,243] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:59,243] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:16:59,243] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:16:59,260] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:59,260] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1651036873, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:16:59,261] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_error_log-0=PartitionData(fetchOffset=672, logStartOffset=7, maxBytes=1048576, currentLeaderEpoch=Optional[9], lastFetchedEpoch=Optional[9]), myfleet_info_log-0=PartitionData(fetchOffset=95, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty), myfleet_error_log-1=PartitionData(fetchOffset=683, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[8], lastFetchedEpoch=Optional[8]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty)}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1651036873, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:17:00,018] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:00,018] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:17:00,018] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:00,422] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:00,422] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:17:00,422] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:01,261] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:17:01,262] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1651036873, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:17:01,262] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_error_log-0=PartitionData(fetchOffset=672, logStartOffset=7, maxBytes=1048576, currentLeaderEpoch=Optional[9], lastFetchedEpoch=Optional[9]), myfleet_info_log-0=PartitionData(fetchOffset=95, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty), myfleet_error_log-1=PartitionData(fetchOffset=683, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[8], lastFetchedEpoch=Optional[8]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty)}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1651036873, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:17:01,954] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:01,954] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:17:01,954] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:02,079] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:02,079] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:17:02,079] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:02,248] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:02,248] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:17:02,248] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:03,262] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:17:03,263] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1651036873, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:17:03,263] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_error_log-0=PartitionData(fetchOffset=672, logStartOffset=7, maxBytes=1048576, currentLeaderEpoch=Optional[9], lastFetchedEpoch=Optional[9]), myfleet_info_log-0=PartitionData(fetchOffset=95, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional[0]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty), myfleet_error_log-1=PartitionData(fetchOffset=683, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[8], lastFetchedEpoch=Optional[8]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[12], lastFetchedEpoch=Optional.empty)}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1651036873, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1188/756706694.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-20 08:17:04,020] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:04,020] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:17:04,021] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:04,681] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:04,681] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-20 08:17:04,681] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:05,329] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-82656 in state PreparingRebalance with old generation 2 (__consumer_offsets-18) (reason: Adding new member consumer-console-consumer-82656-1-e1a66930-57bd-4721-b65f-306bb639f567 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:17:05,330] INFO [GroupCoordinator 87]: Stabilized group console-consumer-82656 generation 3 (__consumer_offsets-18) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:17:05,330] INFO [GroupCoordinator 87]: Assignment received from leader for group console-consumer-82656 for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:17:05,378] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-25563 in state PreparingRebalance with old generation 2 (__consumer_offsets-32) (reason: Adding new member consumer-console-consumer-25563-1-49ac9ed0-bec1-4802-b757-bb84bc54fa0d with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:17:05,379] INFO [GroupCoordinator 87]: Stabilized group console-consumer-25563 generation 3 (__consumer_offsets-32) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:17:05,379] INFO [GroupCoordinator 87]: Assignment received from leader for group console-consumer-25563 for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-08-20 08:17:05,522] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:08,578] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: No route to host (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:09,743] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:09,743] INFO Socket connection established, initiating session, client: /192.168.1.7:38688, server: 192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxn)
[2021-08-20 08:17:09,746] INFO Session establishment complete on server 192.168.1.8/192.168.1.8:2181, sessionid = 0x8001dae61d70001, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
