[2021-08-24 08:21:36,331] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=250600289, epoch=121512) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:36,339] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=250600289, epoch=121512), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:36,574] INFO [GroupCoordinator 87]: Member consumer-console-consumer-9956-1-c640ddb5-d8f2-47ea-869e-a6f77af7ad50 in group console-consumer-9956 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:36,574] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-9956 in state PreparingRebalance with old generation 1 (__consumer_offsets-28) (reason: removing member consumer-console-consumer-9956-1-c640ddb5-d8f2-47ea-869e-a6f77af7ad50 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:36,574] INFO [GroupCoordinator 87]: Group console-consumer-9956 with generation 2 is now empty (__consumer_offsets-28) (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:37,885] INFO [GroupCoordinator 87]: Member consumer-console-consumer-24047-1-495a59a6-b635-4038-81c6-51d094f62c85 in group console-consumer-24047 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:37,885] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-24047 in state PreparingRebalance with old generation 1 (__consumer_offsets-28) (reason: removing member consumer-console-consumer-24047-1-495a59a6-b635-4038-81c6-51d094f62c85 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:37,886] INFO [GroupCoordinator 87]: Group console-consumer-24047 with generation 2 is now empty (__consumer_offsets-28) (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:38,341] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:38,341] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=250600289, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:38,341] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[2]), myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[0]), myfleet_info_log-0=PartitionData(fetchOffset=113, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=687, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=250600289, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:38,818] WARN Client session timed out, have not heard from server in 12001ms for sessionid 0x700005424210000 (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:38,819] INFO Client session timed out, have not heard from server in 12001ms for sessionid 0x700005424210000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:39,156] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:39,156] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:39,156] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:40,018] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:40,018] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:40,018] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:40,342] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:40,342] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=250600289, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:40,342] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[2]), myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[0]), myfleet_info_log-0=PartitionData(fetchOffset=113, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=687, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=250600289, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:41,748] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:41,748] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:41,748] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:42,343] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:42,343] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=250600289, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:42,344] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[2]), myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[0]), myfleet_info_log-0=PartitionData(fetchOffset=113, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=687, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=250600289, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:42,544] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:42,544] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:42,544] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:43,509] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:43,510] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:43,510] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:44,344] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:44,345] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=250600289, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:44,345] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[2]), myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[0]), myfleet_info_log-0=PartitionData(fetchOffset=113, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=687, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=250600289, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:44,723] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:44,724] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:44,724] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:45,195] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:45,195] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:45,195] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:45,557] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:45,557] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:45,557] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:46,345] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:46,346] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=250600289, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:46,346] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[2]), myfleet_user_error_log-0=PartitionData(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[0]), myfleet_info_log-0=PartitionData(fetchOffset=113, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=687, logStartOffset=20, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=250600289, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-24 08:21:47,049] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:47,049] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:47,049] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:47,381] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:47,381] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:47,381] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:47,920] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:47,920] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-24 08:21:47,920] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:48,753] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-9956 in state PreparingRebalance with old generation 2 (__consumer_offsets-28) (reason: Adding new member consumer-console-consumer-9956-1-030c17eb-da52-4d52-b036-369ffaec0aff with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:48,753] INFO [GroupCoordinator 87]: Stabilized group console-consumer-9956 generation 3 (__consumer_offsets-28) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:48,754] INFO [GroupCoordinator 87]: Assignment received from leader for group console-consumer-9956 for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:48,859] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-24047 in state PreparingRebalance with old generation 2 (__consumer_offsets-28) (reason: Adding new member consumer-console-consumer-24047-1-f86548d8-e1e0-4cb5-8479-1e428d2f6a09 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:48,860] INFO [GroupCoordinator 87]: Stabilized group console-consumer-24047 generation 3 (__consumer_offsets-28) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:48,860] INFO [GroupCoordinator 87]: Assignment received from leader for group console-consumer-24047 for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-08-24 08:21:49,632] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:49,632] INFO Socket connection established, initiating session, client: /192.168.1.7:38112, server: 192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:49,634] INFO Unable to read additional data from server sessionid 0x700005424210000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:50,150] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:50,150] INFO Socket connection established, initiating session, client: /192.168.1.7:45218, server: 192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:50,153] INFO Unable to read additional data from server sessionid 0x700005424210000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:51,004] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:51,081] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:52,242] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:52,242] INFO Socket connection established, initiating session, client: /192.168.1.7:38164, server: 192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxn)
[2021-08-24 08:21:52,244] INFO Session establishment complete on server 192.168.1.7/192.168.1.7:2181, sessionid = 0x700005424210000, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
