[2021-08-31 09:02:59,281] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1593185073, epoch=125969) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:02:59,287] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1593185073, epoch=125969), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:02:59,283] WARN Client session timed out, have not heard from server in 6850ms for sessionid 0x700005424210000 (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:02:59,293] INFO Client session timed out, have not heard from server in 6850ms for sessionid 0x700005424210000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:02:59,648] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:02:59,648] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:02:59,648] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:01,288] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:01,288] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1593185073, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:01,288] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1593185073, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:01,295] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:01,295] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:01,295] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:02,053] INFO [GroupCoordinator 87]: Member sedatCode-applicationId-b1e45716-7257-40ff-a1c2-034ac882ace4-StreamThread-1-consumer-56b40599-8a49-4ac1-9644-75bf69cc0115 in group sedatCode-applicationId has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-31 09:03:02,053] INFO [GroupCoordinator 87]: Preparing to rebalance group sedatCode-applicationId in state PreparingRebalance with old generation 21 (__consumer_offsets-0) (reason: removing member sedatCode-applicationId-b1e45716-7257-40ff-a1c2-034ac882ace4-StreamThread-1-consumer-56b40599-8a49-4ac1-9644-75bf69cc0115 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-08-31 09:03:02,053] INFO [GroupCoordinator 87]: Group sedatCode-applicationId with generation 22 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-31 09:03:02,213] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:02,213] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:02,213] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:02,663] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:02,663] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:02,664] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:03,289] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:03,289] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1593185073, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:03,289] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1593185073, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:04,659] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:04,659] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:04,659] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:05,190] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:05,190] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:05,190] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:05,290] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:05,290] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1593185073, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:05,290] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1593185073, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:05,889] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:05,889] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:05,889] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:07,071] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:07,071] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:07,071] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:07,291] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:07,291] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1593185073, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:07,291] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1593185073, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:07,575] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:07,575] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:07,575] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:08,051] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:08,051] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:08,051] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:09,292] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:09,292] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1593185073, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:09,292] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1593185073, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-31 09:03:09,679] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:09,679] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:09,679] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:09,992] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:09,992] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:09,992] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:10,437] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:10,437] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-31 09:03:10,437] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:11,472] INFO [GroupCoordinator 87]: Preparing to rebalance group sedatCode-applicationId in state PreparingRebalance with old generation 22 (__consumer_offsets-0) (reason: Adding new member sedatCode-applicationId-b1e45716-7257-40ff-a1c2-034ac882ace4-StreamThread-1-consumer-5961a06b-91fc-4037-97f8-dd02fe7b1e05 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-31 09:03:11,473] INFO [GroupCoordinator 87]: Stabilized group sedatCode-applicationId generation 23 (__consumer_offsets-0) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-08-31 09:03:11,474] INFO [GroupCoordinator 87]: Assignment received from leader for group sedatCode-applicationId for generation 23. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-08-31 09:03:12,135] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:12,135] INFO Socket connection established, initiating session, client: /192.168.1.7:60990, server: 192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxn)
[2021-08-31 09:03:12,136] INFO Session establishment complete on server 192.168.1.7/192.168.1.7:2181, sessionid = 0x700005424210000, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
