[2021-08-29 09:05:21,212] WARN Client session timed out, have not heard from server in 9105ms for sessionid 0x700005424210000 (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:21,213] INFO Client session timed out, have not heard from server in 9105ms for sessionid 0x700005424210000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:21,213] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1234841643, epoch=136048) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:21,214] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1234841643, epoch=136048), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:21,341] INFO [GroupCoordinator 87]: Member consumer-console-consumer-10015-1-e711e07f-61cb-4c6e-890c-54e5ec5cac81 in group console-consumer-10015 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:21,341] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-10015 in state PreparingRebalance with old generation 9 (__consumer_offsets-48) (reason: removing member consumer-console-consumer-10015-1-e711e07f-61cb-4c6e-890c-54e5ec5cac81 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:21,341] INFO [GroupCoordinator 87]: Group console-consumer-10015 with generation 10 is now empty (__consumer_offsets-48) (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:22,089] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:22,090] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:22,090] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:22,491] INFO [GroupCoordinator 87]: Member sedatCode-applicationId-b1e45716-7257-40ff-a1c2-034ac882ace4-StreamThread-1-consumer-d28a79e5-dea8-4065-b0b5-eff271688601 in group sedatCode-applicationId has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:22,492] INFO [GroupCoordinator 87]: Preparing to rebalance group sedatCode-applicationId in state PreparingRebalance with old generation 17 (__consumer_offsets-0) (reason: removing member sedatCode-applicationId-b1e45716-7257-40ff-a1c2-034ac882ace4-StreamThread-1-consumer-d28a79e5-dea8-4065-b0b5-eff271688601 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:22,492] INFO [GroupCoordinator 87]: Group sedatCode-applicationId with generation 18 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:23,215] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:23,215] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1234841643, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:23,215] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1234841643, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:23,413] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:23,413] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:23,413] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:24,191] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:24,191] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:24,191] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:24,787] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:24,787] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:24,787] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:25,215] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:25,216] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1234841643, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:25,216] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1234841643, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:26,462] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:26,462] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:26,462] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:27,216] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:27,217] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1234841643, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:27,217] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1234841643, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:27,481] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:27,481] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:27,481] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:28,276] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:28,276] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:28,276] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:29,218] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:29,218] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1234841643, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:29,218] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1234841643, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:30,225] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:30,225] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:30,225] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:30,729] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:30,729] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:30,729] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:31,055] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:31,055] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:31,055] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:31,219] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:31,219] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=1234841643, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:31,220] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_sedat001_error_log-1=PartitionData(fetchOffset=9, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_user_error_log-0=PartitionData(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_info_log-0=PartitionData(fetchOffset=139, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[15], lastFetchedEpoch=Optional[14]), myfleet_error_log-1=PartitionData(fetchOffset=698, logStartOffset=683, maxBytes=1048576, currentLeaderEpoch=Optional[11], lastFetchedEpoch=Optional[11])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1234841643, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1392/1510134288.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-08-29 09:05:32,178] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:32,179] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:32,179] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:33,037] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:33,037] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-08-29 09:05:33,037] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:33,349] INFO [GroupCoordinator 87]: Preparing to rebalance group sedatCode-applicationId in state PreparingRebalance with old generation 18 (__consumer_offsets-0) (reason: Adding new member sedatCode-applicationId-b1e45716-7257-40ff-a1c2-034ac882ace4-StreamThread-1-consumer-507b8ee6-9be6-4995-b4c9-3522ea4b0314 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:33,350] INFO [GroupCoordinator 87]: Stabilized group sedatCode-applicationId generation 19 (__consumer_offsets-0) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:33,350] INFO [GroupCoordinator 87]: Assignment received from leader for group sedatCode-applicationId for generation 19. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:33,627] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:33,635] INFO [GroupCoordinator 87]: Preparing to rebalance group console-consumer-10015 in state PreparingRebalance with old generation 10 (__consumer_offsets-48) (reason: Adding new member consumer-console-consumer-10015-1-4dfab6b8-c109-4edc-bcb8-9d2626ea52b2 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:33,636] INFO [GroupCoordinator 87]: Stabilized group console-consumer-10015 generation 11 (__consumer_offsets-48) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:33,636] INFO [GroupCoordinator 87]: Assignment received from leader for group console-consumer-10015 for generation 11. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-08-29 09:05:36,705] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: No route to host (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:38,433] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:38,433] INFO Socket connection established, initiating session, client: /192.168.1.7:44454, server: 192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxn)
[2021-08-29 09:05:38,435] INFO Session establishment complete on server 192.168.1.7/192.168.1.7:2181, sessionid = 0x700005424210000, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
