[2021-07-23 17:03:02,675] WARN Client session timed out, have not heard from server in 12003ms for sessionid 0x7001a50a1bf0000 (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:02,676] INFO Client session timed out, have not heard from server in 12003ms for sessionid 0x7001a50a1bf0000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:03,677] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:03,677] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:03,677] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:04,340] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:04,340] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:04,340] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:05,457] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:05,457] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:05,457] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:06,313] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:06,313] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:06,313] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:07,033] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:07,033] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:07,033] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:09,108] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:09,108] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:09,108] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:10,121] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:10,121] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:10,121] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:11,090] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:11,090] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:11,090] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:12,263] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:12,263] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:12,263] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:12,699] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:12,699] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:12,699] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:13,678] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:13,678] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:13,678] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:14,962] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:14,962] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:14,962] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:15,468] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:15,468] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:15,468] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:16,411] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:16,411] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:16,411] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:17,712] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:17,712] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:17,712] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:18,337] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:18,337] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:18,337] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:18,749] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:18,749] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:18,749] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:20,052] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:20,052] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:20,052] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:20,219] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:20,219] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:20,219] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:20,369] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:20,370] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:20,370] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:22,393] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:22,394] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:22,394] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:22,865] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:22,866] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:22,866] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:23,465] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=418083243, epoch=40323) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:23,465] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=418083243, epoch=40323), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 88 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:23,595] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:23,596] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:23,596] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:24,818] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:24,819] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:24,819] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:24,961] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:24,961] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:24,961] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:25,466] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:25,466] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=418083243, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:25,466] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_error_log-0=PartitionData(fetchOffset=7, logStartOffset=3, maxBytes=1048576, currentLeaderEpoch=Optional[4], lastFetchedEpoch=Optional[4]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3]), myfleet_error_log-1=PartitionData(fetchOffset=20, logStartOffset=13, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=418083243, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:25,538] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:25,538] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:25,538] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:27,283] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:27,284] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:27,284] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:27,467] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:27,467] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=418083243, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:27,467] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_error_log-0=PartitionData(fetchOffset=7, logStartOffset=3, maxBytes=1048576, currentLeaderEpoch=Optional[4], lastFetchedEpoch=Optional[4]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3]), myfleet_error_log-1=PartitionData(fetchOffset=20, logStartOffset=13, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=418083243, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:28,322] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:28,323] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:28,323] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:29,295] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:29,295] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:29,295] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:29,468] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:29,468] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=418083243, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:29,468] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_error_log-0=PartitionData(fetchOffset=7, logStartOffset=3, maxBytes=1048576, currentLeaderEpoch=Optional[4], lastFetchedEpoch=Optional[4]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3]), myfleet_error_log-1=PartitionData(fetchOffset=20, logStartOffset=13, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=418083243, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:30,662] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:30,663] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:30,663] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:31,469] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:31,469] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=418083243, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:31,469] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_error_log-0=PartitionData(fetchOffset=7, logStartOffset=3, maxBytes=1048576, currentLeaderEpoch=Optional[4], lastFetchedEpoch=Optional[4]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3]), myfleet_error_log-1=PartitionData(fetchOffset=20, logStartOffset=13, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=418083243, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:31,702] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:31,703] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:31,703] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:31,961] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:31,961] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:31,961] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:33,125] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:33,125] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:33,125] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:33,470] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:33,470] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=418083243, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:33,471] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_error_log-0=PartitionData(fetchOffset=7, logStartOffset=3, maxBytes=1048576, currentLeaderEpoch=Optional[4], lastFetchedEpoch=Optional[4]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3]), myfleet_error_log-1=PartitionData(fetchOffset=20, logStartOffset=13, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=418083243, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:33,537] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:33,537] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:33,537] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:34,467] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:34,467] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:34,467] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:35,471] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error connecting to node 192.168.1.8:9092 (id: 88 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:987)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:35,472] INFO [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error sending fetch request (sessionId=418083243, epoch=INITIAL) to node 88: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:35,472] WARN [ReplicaFetcher replicaId=87, leaderId=88, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=87, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={myfleet_error_log-0=PartitionData(fetchOffset=7, logStartOffset=3, maxBytes=1048576, currentLeaderEpoch=Optional[4], lastFetchedEpoch=Optional[4]), myfleet_CAR-1=PartitionData(fetchOffset=160, logStartOffset=160, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3]), myfleet_error_log-1=PartitionData(fetchOffset=20, logStartOffset=13, maxBytes=1048576, currentLeaderEpoch=Optional[3], lastFetchedEpoch=Optional[3]), myfleet_CAR-0=PartitionData(fetchOffset=163, logStartOffset=163, maxBytes=1048576, currentLeaderEpoch=Optional[7], lastFetchedEpoch=Optional[3])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=418083243, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.1.8:9092 (id: 88 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:105)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread$$Lambda$1232/146728001.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-07-23 17:03:36,079] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:36,079] ERROR Unable to open socket to {}192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:36,079] INFO Socket error occurred: 192.168.1.8/192.168.1.8:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:36,775] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:36,775] ERROR Unable to open socket to {}192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:36,775] INFO Socket error occurred: 192.168.1.7/192.168.1.7:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:37,141] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:37,141] ERROR Unable to open socket to {}192.168.1.4/192.168.1.4:2181 (org.apache.zookeeper.ClientCnxnSocketNIO)
[2021-07-23 17:03:37,141] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: Network is unreachable (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:38,390] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:38,390] INFO Socket connection established, initiating session, client: /192.168.1.7:40854, server: 192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:38,393] INFO Unable to read additional data from server sessionid 0x7001a50a1bf0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:38,919] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:38,919] INFO Socket connection established, initiating session, client: /192.168.1.7:52432, server: 192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:38,920] INFO Unable to read additional data from server sessionid 0x7001a50a1bf0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:39,370] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:42,439] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: No route to host (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:44,259] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:44,259] INFO Socket connection established, initiating session, client: /192.168.1.7:40898, server: 192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:44,261] INFO Unable to read additional data from server sessionid 0x7001a50a1bf0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:45,196] INFO Opening socket connection to server 192.168.1.7/192.168.1.7:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:45,196] INFO Socket connection established, initiating session, client: /192.168.1.7:52480, server: 192.168.1.7/192.168.1.7:2181 (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:45,197] INFO Unable to read additional data from server sessionid 0x7001a50a1bf0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:45,898] INFO Opening socket connection to server 192.168.1.4/192.168.1.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:48,963] INFO Socket error occurred: 192.168.1.4/192.168.1.4:2181: No route to host (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:50,524] INFO Opening socket connection to server 192.168.1.8/192.168.1.8:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:50,525] INFO Socket connection established, initiating session, client: /192.168.1.7:40942, server: 192.168.1.8/192.168.1.8:2181 (org.apache.zookeeper.ClientCnxn)
[2021-07-23 17:03:50,528] INFO Session establishment complete on server 192.168.1.8/192.168.1.8:2181, sessionid = 0x7001a50a1bf0000, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
